## Exercise1 ##

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
# 1. Load the dataset
# Note: The provided heart.csv seems to have some formatting issues in the preview 
# (e.g., merged columns). We assume standard UCI Heart Disease format columns:
# age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target
try:
    df = pd.read_csv('heart.csv')
except Exception as e:
    print(f"Error loading heart.csv: {e}")
    # Fallback: If the CSV is malformed, you might need to clean it manually. 
    # For this code, we assume the standard column names exist.
    pass

# Check columns (Adjust if your specific CSV has different headers)
print("Columns in Heart Dataset:", df.columns.tolist())

# Define features (X) and target (y)
# Assuming 'target' is the last column or named 'target'
if 'target' in df.columns:
    feature_cols = [col for col in df.columns if col != 'target']
else:
    # Fallback if header is missing or different, assuming last column is target
    feature_cols = df.columns[:-1]
    
X = df[feature_cols]
y = df['target'] if 'target' in df.columns else df.iloc[:, -1]

# Handle any missing values if present
X.dropna(inplace=True)
y = y[X.index]

# 2. Split the dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. Preprocessing: Scale the features
# SVM is sensitive to feature scales, so StandardScaler is recommended even with Linear Kernel
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Train SVM with Linear Kernel
svm_model = SVC(kernel='linear', C=1.0, random_state=42)
svm_model.fit(X_train_scaled, y_train)

# 5. Evaluate Performance
y_pred = svm_model.predict(X_test_scaled)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\n--- Problem 1: Heart Disease Prediction Results ---")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['No Disease (0)', 'Disease (1)']))

# 6. Prediction Function for New Data
def predict_heart_disease(new_data_array):
    """
    Predicts heart disease presence for new data.
    Input: new_data_array should be a 2D array-like object with the same features as training data.
    Output: Prediction (0 or 1)
    """
    # Convert to numpy array if not already
    new_data_np = np.array(new_data_array).reshape(1, -1)
    
    # Scale the new data using the SAME scaler fitted on training data
    new_data_scaled = scaler.transform(new_data_np)
    
    # Predict
    prediction = svm_model.predict(new_data_scaled)
    return prediction[0]

# Example Usage:
# Take the first sample from the test set as an example "new patient"
sample_patient = X_test.iloc[0].values
pred_result = predict_heart_disease(sample_patient)
actual_result = y_test.iloc[0]
print(f"\nExample Prediction:")
print(f"Patient Features: {sample_patient[:3]}... (truncated)")
print(f"Predicted Class: {pred_result}")
print(f"Actual Class:    {actual_result}")

Columns in Heart Dataset: ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

--- Problem 1: Heart Disease Prediction Results ---
Precision: 0.7638
Recall:    0.9238
F1-Score:  0.8362

Classification Report:
                precision    recall  f1-score   support

No Disease (0)       0.90      0.70      0.79       100
   Disease (1)       0.76      0.92      0.84       105

      accuracy                           0.81       205
     macro avg       0.83      0.81      0.81       205
  weighted avg       0.83      0.81      0.81       205


Example Prediction:
Patient Features: [64.  1.  0.]... (truncated)
Predicted Class: 0
Actual Class:    0


C:\Users\ASUS TUF GAMING A15\AppData\Local\Temp\ipykernel_8288\3245840944.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)
c:\Users\ASUS TUF GAMING A15\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


## Exercise2 ##

In [3]:
X_tr, X_te, y_tr, y_te = pd.read_csv("Khan_xtrain.csv"), pd.read_csv("Khan_xtest.csv"), pd.read_csv("Khan_ytrain.csv"), pd.read_csv("Khan_ytest.csv")

In [6]:
X_tr.shape, X_te.shape, y_tr.shape, y_te.shape

((63, 2309), (20, 2309), (63, 2), (20, 2))

In [7]:
X_tr.head(), y_tr.head()

(  Unnamed: 0        V1        V2        V3        V4        V5        V6  \
 0         V1  0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809   
 1         V2 -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488   
 2         V3 -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474   
 3         V4  0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687   
 4         V5  0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936   
 
          V7        V8        V9  ...     V2299     V2300     V2301     V2302  \
 0  1.342604  0.057042  0.133569  ... -0.238511 -0.027474 -1.660205  0.588231   
 1  1.429498 -0.120249  0.456792  ... -0.657394 -0.246284 -0.836325 -0.571284   
 2  1.159300  0.015676  0.191942  ... -0.696352  0.024985 -1.059872 -0.403767   
 3  1.093801  0.819736 -0.284620  ...  0.259746  0.357115 -1.893128  0.255107   
 4  1.251219  0.771450  0.030917  ... -0.200404  0.061753 -2.273998 -0.039365   
 
       V2303     V2304     V2305     V2306     V

In [8]:
y_tr = y_tr.values.astype('int').ravel()
y_te = y_te.values.astype('int').ravel()

In [ ]:
if 'Unnamed: 0' in X_tr.columns:
    X_tr.drop(columns=['Unnamed: 0'], inplace=True)

if 'Unnamed: 0' in X_te.columns:
    X_te.drop(columns=['Unnamed: 0'], inplace=True)

y

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import os

print("=" * 60)
print("PROBLEM 2: KHAN GENE EXPRESSION DATA")
print("=" * 60)

# 1. Load Features
print("\nLoading data...")
try:
    X_train = pd.read_csv('Khan_xtrain.csv', index_col=0)
    X_test = pd.read_csv('Khan_xtest.csv', index_col=0)
    
    print(f"✓ Training data shape: {X_train.shape}")
    print(f"✓ Test data shape: {X_test.shape}")
    
except Exception as e:
    print(f"✗ Error loading data: {e}")
    raise

# 2. Manually construct y_train labels (Standard Khan Dataset)
# The Khan dataset has 63 training samples with 4 classes:
# - Samples 1-23: Class 2 (Ewing sarcoma) 
# - Samples 24-43: Class 4 (Rhabdomyosarcoma)
# - Samples 44-55: Class 3 (Neuroblastoma)
# - Samples 56-63: Class 1 (Burkitt lymphoma)

print("\nConstructing training labels...")
y_train = np.array(
    [2]*23 +   # Ewing sarcoma (samples 1-23)
    [4]*20 +   # Rhabdomyosarcoma (samples 24-43)
    [3]*12 +   # Neuroblastoma (samples 44-55)
    [1]*8      # Burkitt lymphoma (samples 56-63)
)

print(f"✓ Training labels shape: {y_train.shape}")
print(f"✓ Unique classes: {np.unique(y_train)}")
print(f"✓ Class distribution:")
for cls in sorted(np.unique(y_train)):
    count = np.sum(y_train == cls)
    print(f"  Class {cls}: {count} samples")

# 3. Preprocessing - Scale the features
print("\nScaling features...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("✓ Features scaled successfully")

# 4. Train SVM with Linear Kernel
print("\nTraining SVM with linear kernel...")
svm_model = SVC(kernel='linear', C=1.0, random_state=42)
svm_model.fit(X_train_scaled, y_train)
print("✓ Model trained successfully")

# 5. Evaluate on Training Set
print("\n" + "=" * 60)
print("TRAINING SET PERFORMANCE")
print("=" * 60)
y_train_pred = svm_model.predict(X_train_scaled)
train_acc = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_acc:.4f} ({train_acc*100:.2f}%)")
print(f"\nTraining Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))

# 6. Evaluate on Test Set
print("\n" + "=" * 60)
print("TEST SET PERFORMANCE")
print("=" * 60)

# Try to load y_test if available
y_test = None
if os.path.exists('Khan_ytest.csv'):
    try:
        y_test_df = pd.read_csv('Khan_ytest.csv', index_col=0, header=None)
        y_test = y_test_df.values.flatten()
        print(f"✓ Test labels loaded: {len(y_test)} samples")
    except Exception as e:
        print(f"✗ Could not load test labels: {e}")
        print("  Using standard Khan test labels...")
        # Standard Khan test set has 20 samples:
        # - Samples 1-6: Class 2
        # - Samples 7-11: Class 4
        # - Samples 12-17: Class 3
        # - Samples 18-20: Class 1
        y_test = np.array([2]*6 + [4]*5 + [3]*6 + [1]*3)
        print(f"  Using constructed test labels: {len(y_test)} samples")
else:
    print("⚠ Khan_ytest.csv not found")
    print("  Using standard Khan test labels...")
    # Standard Khan test set has 20 samples
    y_test = np.array([2]*6 + [4]*5 + [3]*6 + [1]*3)
    print(f"  Using constructed test labels: {len(y_test)} samples")

# Make predictions on test set
y_test_pred = svm_model.predict(X_test_scaled)

# Calculate metrics
test_acc = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)

print(f"\nTest Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")
print(f"\nTest Confusion Matrix:")
print(conf_matrix)

# Class names for better reporting
class_names = {
    1: 'Burkitt lymphoma',
    2: 'Ewing sarcoma',
    3: 'Neuroblastoma',
    4: 'Rhabdomyosarcoma'
}

print(f"\nDetailed Classification Report:")
print(classification_report(y_test, y_test_pred, 
                            target_names=[class_names[c] for c in sorted(class_names.keys())]))

# Summary
print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print(f"Training Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:     {test_acc:.4f}")
print(f"\nModel successfully trained on {X_train.shape[0]} samples")
print(f"with {X_train.shape[1]} gene features each")
print(f"using SVM with linear kernel")

PROBLEM 2: KHAN GENE EXPRESSION DATA

Loading data...
✓ Training data shape: (63, 2308)
✓ Test data shape: (20, 2308)

Constructing training labels...
✓ Training labels shape: (63,)
✓ Unique classes: [1 2 3 4]
✓ Class distribution:
  Class 1: 8 samples
  Class 2: 23 samples
  Class 3: 12 samples
  Class 4: 20 samples

Scaling features...
✓ Features scaled successfully

Training SVM with linear kernel...
✓ Model trained successfully

TRAINING SET PERFORMANCE
Training Accuracy: 1.0000 (100.00%)

Training Confusion Matrix:
[[ 8  0  0  0]
 [ 0 23  0  0]
 [ 0  0 12  0]
 [ 0  0  0 20]]

TEST SET PERFORMANCE
✓ Test labels loaded: 21 samples


ValueError: Found input variables with inconsistent numbers of samples: [21, 20]